<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="jeeveslaptop" failures="1" tests="1" name="orderTest" time="33.303" errors="0" timestamp="2022-11-22T12:57:45 IST">
  <testcase classname="AvactisTestCases.OrdersTest" name="UpdateOrderStatus" time="30.01">
    <failure type="java.lang.AssertionError" message="expected [Order data has been updted] but found [Order data has been updated]">
      <![CDATA[java.lang.AssertionError: expected [Order data has been updted] but found [Order data has been updated]
at AvactisTestCases.OrdersTest.UpdateOrderStatus(OrdersTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UpdateOrderStatus -->
</testsuite> <!-- orderTest -->
